variables:
    PROJECTPATH: "src/APE.PostgreSQL.Teamwork.sln"
    DEPLOYCONFIGURATION: "Release"

before_script:
    - REM NuGet     
    - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\RestoreNugetPackages.ps1
Build:
    stage: build
    artifacts:
        when: on_success
        expire_in: 30 mins
        paths:
            - src\*\bin\%DEPLOYCONFIGURATION%
    script: 
        - REM WriteBuildVersionToAssemblyInfo.ps1
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\WriteBuildVersionToAssemblyInfo.ps1 %CI_PROJECT_NAME% %CI_COMMIT_REF_NAME% %CI_COMMIT_SHA% %CI_REPOSITORY_URL%

        - REM MSBuild
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\CallMsBuild.ps1 -treatWarningAsErrors true -codeAnalysisTreatWarningsAsErrors true

UnitTest:
    stage: test
    script: 
        - REM MSTest 
        - echo on
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\UnitTests\RunUnittests.ps1

CreateNugetPackage:
    stage: deploy
    only:
        - master
    #when: manual
    script:
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\BuildNugetPakages.ps1


        - REM Copy Executables
        - del /S /Q "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.GUI\bin\Release\* "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork"
        - del /S /Q "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork.CommandPrompt"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.CommandPrompt\bin\Release\* "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork.CommandPrompt"
        - del /S /Q "C:\NuGetOwncloud\Customer\Loepfe\MillMasterTOP\APE.PostgreSQL.Teamwork"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.GUI\bin\Release\* "C:\NuGetOwncloud\Customer\Loepfe\MillMasterTOP\APE.PostgreSQL.Teamwork"
    environment:
        name: NuGetBuilds