variables:
    PROJECTPATH: "src/APE.PostgreSQL.Teamwork.sln"
    DEPLOYCONFIGURATION: "Release"

before_script:
    - REM NuGet     
    - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\RestoreNugetPackages.ps1
Build:
    stage: build
    artifacts:
        when: on_success
        expire_in: 30 mins
        paths:
            - src\*\bin\%DEPLOYCONFIGURATION%
    script: 
        - REM WriteBuildVersionToAssemblyInfo.ps1
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\WriteBuildVersionToAssemblyInfo.ps1 %CI_PROJECT_NAME% %CI_COMMIT_REF_NAME% %CI_COMMIT_SHA% %CI_REPOSITORY_URL%

        - REM MSBuild
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\CallMsBuild.ps1 -treatWarningAsErrors true -codeAnalysisTreatWarningsAsErrors true

UnitTest:
    stage: test
    script: 
        - REM MSTest 
        - echo on
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\UnitTests\RunUnittests.ps1

CreateNugetPackage:
    stage: deploy
    only:
        - master
    #when: manual
    script:
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\Build\BuildNugetPakages.ps1

        - REM APE.PostgreSQL.Teamwork.Tool is a meta package containing only tools!
        - REM Therefore a not automated creation will be used
        - set BUILD_VERSION=0
        - for /f "delims=" %%a in ('powershell -noprofile -command ". C:\NuGetOwncloud\GitlabBuildHelpers\Build\CreateBuildVersion.ps1; GetBuildVersion %CI_PROJECT_NAME% %CI_COMMIT_SHA%;"') do Set "BUILD_VERSION=%%a"
        - powershell -noprofile -command "(Get-Content .\src\APE.PostgreSQL.Teamwork.Tool\APE.PostgreSQL.Teamwork.Tool.nuspec).replace('$version$', '1.0.%BUILD_VERSION%.0') | Set-Content .\src\APE.PostgreSQL.Teamwork.Tool\APE.PostgreSQL.Teamwork.Tool.nuspec"
        - src\.nuget\NuGet.exe pack .\src\APE.PostgreSQL.Teamwork.Tool\APE.PostgreSQL.Teamwork.Tool.nuspec -Prop Configuration=%DEPLOYCONFIGURATION% -OutputDirectory C:\NuGetOwncloud\NuGet\APE.PostgreSQL.Teamwork

        - REM Copy Executables
        - del /S /Q "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.GUI\bin\Release\* "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork"
        - del /S /Q "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork.CommandPrompt"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.CommandPrompt\bin\Release\* "C:\NuGetOwncloud\APE Tools\APE.PostgreSQL.Teamwork.CommandPrompt"
        - del /S /Q "C:\NuGetOwncloud\Customer\Loepfe\MillMasterTOP\APE.PostgreSQL.Teamwork"
        - xcopy /E /V /Y src\APE.PostgreSQL.Teamwork.GUI\bin\Release\* "C:\NuGetOwncloud\Customer\Loepfe\MillMasterTOP\APE.PostgreSQL.Teamwork"
    environment:
        name: NuGetBuilds