before_script:
    - REM NuGet     
    - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\RestoreNugetPackages.ps1 
Build:
    stage: build
    artifacts:
        when: on_success
        expire_in: 30 mins
        paths:
            - src\*\bin\Release
    script: 
        - REM WriteBuildVersionToAssemblyInfo.ps1
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\WriteBuildVersionToAssemblyInfo.ps1 %CI_PROJECT_NAME% %CI_BUILD_REF_NAME% %CI_BUILD_REF% %CI_BUILD_REPO%

        - REM MSBuild
        - msbuild src\NugetPackage.sln /verbosity:normal /p:Configuration=Release /maxcpucount:4

UnitTest:
    stage: test
    script: 
        - REM MSTest 
        - echo on
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\RunUnittests.ps1

CreateNugetPackage:
    stage: deploy
    only:
        - master
    #when: manual
    script:
        - powershell -noprofile -command C:\NuGetOwncloud\GitlabBuildHelpers\BuildNugetPakages.ps1
    environment:
        name: NuGetBuilds