// <auto-generated>
//     This code was generated by the APE CodeGeneration.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using APE.PostgreSQL.Teamwork.ViewModel;
using APE.PostgreSQL.Teamwork.ViewModel.TestHelper;

namespace APE.PostgreSQL.Teamwork.GUI
{
    // APE.CodeGeneration.Attribute [CtorParameter(typeof(IProcessManager))]
    // APE.CodeGeneration.Attribute [CtorParameter(AccessModifier.Private, typeof(DatabaseDisplayData), "selectedDatabase")]
    public partial class ImportWindow {
        //ncrunch: no coverage start

        //--------------------------------------------------------------------------------
        // generated code for CtorParameter
        //--------------------------------------------------------------------------------


        /// <summary>
        /// 
        /// </summary>
        private IProcessManager processManager;

        /// <summary>
        /// 
        /// </summary>
        private DatabaseDisplayData selectedDatabase;

        public ImportWindow(IProcessManager processManager, DatabaseDisplayData selectedDatabase)
        {
            if (processManager == null)
                throw new System.ArgumentNullException("processManager", "processManager == null");
            this.processManager = processManager;

            if (selectedDatabase == null)
                throw new System.ArgumentNullException("selectedDatabase", "selectedDatabase == null");
            this.selectedDatabase = selectedDatabase;

            this.ImportWindowCtor();
        }

        partial void ImportWindowCtor();
        //ncrunch: no coverage end
    }
}
