// <auto-generated>
//     This code was generated by the APE CodeGeneration.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using APE.CodeGeneration.Attributes;

namespace APE.PostgreSQL.Teamwork.ViewModel
{
    // APE.CodeGeneration.Attribute [NotifyProperty(typeof(SQLFileDisplayData), "DiffFile")]
    // APE.CodeGeneration.Attribute [NotifyProperty(typeof(SQLFileDisplayData), "UndoDiffFile")]
    // APE.CodeGeneration.Attribute [NotifyPropertySupport]
    public partial class ExportWindowViewModel
  : System.ComponentModel.INotifyPropertyChanged
    {
        //ncrunch: no coverage start

        //--------------------------------------------------------------------------------
        // generated code for NotifyProperty
        //--------------------------------------------------------------------------------

        protected static readonly System.ComponentModel.PropertyChangedEventArgs DiffFileEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(DiffFile));
        private SQLFileDisplayData diffFile;

        public SQLFileDisplayData DiffFile
        {
            get
            {
                return this.diffFile;
            }
            set
            {
                if (!object.Equals(this.diffFile, value))
                {
                    this.DiffFileBeforeSet(value);
                    this.diffFile = value;
                    this.OnPropertyChanged(DiffFileEventArgs);
                    this.DiffFileAfterSet();
                }
            }
        }

        partial void DiffFileBeforeSet(SQLFileDisplayData newValue);
        partial void DiffFileAfterSet();
        

        protected static readonly System.ComponentModel.PropertyChangedEventArgs UndoDiffFileEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(UndoDiffFile));
        private SQLFileDisplayData undoDiffFile;

        public SQLFileDisplayData UndoDiffFile
        {
            get
            {
                return this.undoDiffFile;
            }
            set
            {
                if (!object.Equals(this.undoDiffFile, value))
                {
                    this.UndoDiffFileBeforeSet(value);
                    this.undoDiffFile = value;
                    this.OnPropertyChanged(UndoDiffFileEventArgs);
                    this.UndoDiffFileAfterSet();
                }
            }
        }

        partial void UndoDiffFileBeforeSet(SQLFileDisplayData newValue);
        partial void UndoDiffFileAfterSet();
        

        //--------------------------------------------------------------------------------
        // generated code for NotifyPropertySupport
        //--------------------------------------------------------------------------------

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            this.PropertyChanged?.Invoke(this, e);
        }

        //ncrunch: no coverage end
    }
}
