// <auto-generated>
//     This code was generated by the APE CodeGeneration.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using APE.CodeGeneration.Attributes;
using APE.PostgreSQL.Teamwork.Model.Setting;
using APE.PostgreSQL.Teamwork.ViewModel;
using Dapper;
using log4net;
using Npgsql;

namespace APE.PostgreSQL.Teamwork
{
    // APE.CodeGeneration.Attribute [Disposable]
    public partial class ConnectionManager  : System.IDisposable
    {
        //ncrunch: no coverage start

        //--------------------------------------------------------------------------------
        // generated code for Disposable
        //--------------------------------------------------------------------------------

        private bool isDisposed = false;

        /// <summary>
        /// Performs application-defined tasks associated with
        /// freeing, releasing or resetting unmanaged resources.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Justification = "False positive. IDisposable is implemented via partial method.")]
        public void Dispose()
        {
            if (this.isDisposed)
                return;

            this.Dispose(true);
            System.GC.SuppressFinalize(this); //do not execute destructor
            this.isDisposed = true;
        }

        /// <summary>
        /// Release unmanaged and - optionally - managed resources
        /// </summary>
        /// <param name="threadSpecificCleanup"><c>true</c> means that the method is calld by the owning thread;
        /// <c>false</c> means it is called by the finalizer thread
        /// resources.</param>
        partial void Dispose(bool threadSpecificCleanup);

        ~ConnectionManager()
        {
            if (this.isDisposed)
                return;

            this.Dispose(false);
            this.isDisposed = true;
        }

        //ncrunch: no coverage end
    }
}
