// <auto-generated>
//     This code was generated by the APE CodeGeneration.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APE.CodeGeneration.Attributes;
using APE.PostgreSQL.Teamwork.Model;

namespace APE.PostgreSQL.Teamwork.ViewModel
{
    // APE.CodeGeneration.Attribute [NotifyProperty(typeof(DatabaseVersion), "NewVersion")]
    // APE.CodeGeneration.Attribute [NotifyProperty(typeof(bool), "Loading")]
    // APE.CodeGeneration.Attribute [CtorParameter(AccessModifier.Public, typeof(Database))]
    // APE.CodeGeneration.Attribute [NotifyPropertySupport]
    public partial class CreateMinorVersionViewModel
  : System.ComponentModel.INotifyPropertyChanged
    {
        //ncrunch: no coverage start

        //--------------------------------------------------------------------------------
        // generated code for CtorParameter
        //--------------------------------------------------------------------------------


        /// <summary>
        /// 
        /// </summary>
        public Database Database { get; set; }

        public CreateMinorVersionViewModel(Database Database)
        {
            if (Database == null)
                throw new System.ArgumentNullException("Database", "Database == null");
            this.Database = Database;

            this.CreateMinorVersionViewModelCtor();
        }

        partial void CreateMinorVersionViewModelCtor();
        //--------------------------------------------------------------------------------
        // generated code for NotifyProperty
        //--------------------------------------------------------------------------------

        protected static readonly System.ComponentModel.PropertyChangedEventArgs NewVersionEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(NewVersion));
        private DatabaseVersion newVersion;

        /// <summary>
        /// 
        /// </summary>
        public DatabaseVersion NewVersion
        {
            get
            {
                return this.newVersion;
            }
            set
            {
                if (!object.Equals(this.newVersion, value))
                {
                    //this.NewVersionChanging(value);
                    this.NewVersionBeforeSet(value);
                    this.newVersion = value;
                    this.OnPropertyChanged(NewVersionEventArgs);
                    //this.NewVersionChanged();
                    this.NewVersionAfterSet();
                }
            }
        }

        partial void NewVersionBeforeSet(DatabaseVersion newValue);
        partial void NewVersionAfterSet();

        //protected virtual void NewVersionChanging(DatabaseVersion newValue) { }
        //protected virtual void NewVersionChanged() { }

        protected static readonly System.ComponentModel.PropertyChangedEventArgs LoadingEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(Loading));
        private bool loading;

        /// <summary>
        /// 
        /// </summary>
        public bool Loading
        {
            get
            {
                return this.loading;
            }
            set
            {
                if (!object.Equals(this.loading, value))
                {
                    //this.LoadingChanging(value);
                    this.LoadingBeforeSet(value);
                    this.loading = value;
                    this.OnPropertyChanged(LoadingEventArgs);
                    //this.LoadingChanged();
                    this.LoadingAfterSet();
                }
            }
        }

        partial void LoadingBeforeSet(bool newValue);
        partial void LoadingAfterSet();

        //protected virtual void LoadingChanging(bool newValue) { }
        //protected virtual void LoadingChanged() { }

        //--------------------------------------------------------------------------------
        // generated code for NotifyPropertySupport
        //--------------------------------------------------------------------------------

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            this.PropertyChanged?.Invoke(this, e);
        }

        //ncrunch: no coverage end
    }
}
