// <auto-generated>
//     This code was generated by the APE CodeGeneration.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
using System;
using System.IO;
using APE.CodeGeneration.Attributes;
using Npgsql;

namespace APE.PostgreSQL.Teamwork.ViewModel
{
    // APE.CodeGeneration.Attribute [NotifyProperty(AccessModifier.PublicGetPrivateSet, typeof(string), "SQL")]
    // APE.CodeGeneration.Attribute [NotifyProperty(AccessModifier.PublicGetPrivateSet, typeof(string), "Title")]
    // APE.CodeGeneration.Attribute [NotifyPropertySupport]
    public partial class Statement  : System.ComponentModel.INotifyPropertyChanged
    {
        //ncrunch: no coverage start

        //--------------------------------------------------------------------------------
        // generated code for NotifyProperty
        //--------------------------------------------------------------------------------

        protected static readonly System.ComponentModel.PropertyChangedEventArgs SQLEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(SQL));
        private string sQL;

        /// <summary>
        /// 
        /// </summary>
        public string SQL
        {
            get
            {
                return this.sQL;
            }
            private set
            {
                if (!object.Equals(this.sQL, value))
                {
                    //this.SQLChanging(value);
                    this.SQLBeforeSet(value);
                    this.sQL = value;
                    this.OnPropertyChanged(SQLEventArgs);
                    //this.SQLChanged();
                    this.SQLAfterSet();
                }
            }
        }

        partial void SQLBeforeSet(string newValue);
        partial void SQLAfterSet();

        //protected virtual void SQLChanging(string newValue) { }
        //protected virtual void SQLChanged() { }

        protected static readonly System.ComponentModel.PropertyChangedEventArgs TitleEventArgs = new System.ComponentModel.PropertyChangedEventArgs(nameof(Title));
        private string title;

        /// <summary>
        /// 
        /// </summary>
        public string Title
        {
            get
            {
                return this.title;
            }
            private set
            {
                if (!object.Equals(this.title, value))
                {
                    //this.TitleChanging(value);
                    this.TitleBeforeSet(value);
                    this.title = value;
                    this.OnPropertyChanged(TitleEventArgs);
                    //this.TitleChanged();
                    this.TitleAfterSet();
                }
            }
        }

        partial void TitleBeforeSet(string newValue);
        partial void TitleAfterSet();

        //protected virtual void TitleChanging(string newValue) { }
        //protected virtual void TitleChanged() { }

        //--------------------------------------------------------------------------------
        // generated code for NotifyPropertySupport
        //--------------------------------------------------------------------------------

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            this.PropertyChanged?.Invoke(this, e);
        }

        //ncrunch: no coverage end
    }
}
